### ISSUE TITLE
restore errors

### ISSUE THREAD

**Issue by karpa13a** [DeviaVir/cassandras3#3]
C* is 3.11.2
1. somehow restored table dir placed in root of /var/lib/cassandra/data instead /var/lib/cassandra/data/keyspace
2. after restoration /subj/ tryin to issue command:
```
sh.ErrorReturnCode_1:

  RAN: /usr/bin/nodetool -h 127.0.0.1 -p 7199 refresh test testtable-6e1be52040aa11e8863cbb5e9bd5fe43

  STDOUT:
nodetool: Unknown keyspace/cf pair (test.testtable-6e1be52040aa11e8863cbb5e9bd5fe43)
See 'nodetool help' or 'nodetool help <command>'.
```

instead of /usr/bin/nodetool -h 127.0.0.1 -p 7199 refresh test testtable (ommiting uuid)
